"""Generate beebasm source for the ink lookup tables from the canonical table."""

from __future__ import annotations

from dontdither.inks import (
    INKS,
    LOGICAL_COLOUR,
    PHYSICAL_COLOUR,
    InkTable,
    mode1_byte,
    pattern_rows_as_mode1_bytes,
)

# Marker in pattern_to_state for a 2x2 arrangement that is not a canonical ink.
NON_CANONICAL = 0xFF


def superpixel_index(pattern: str) -> int:
    """The pattern_to_state index of a literal 2x2 pattern.

    The index is itself a MODE 1 byte whose four pixels, left to right, are
    TL, TR, BL, BR. The 6502 forms it from the top and bottom raster bytes:
        even sx:  (top AND &CC) OR ((bottom AND &CC) >> 2)
        odd sx:   ((top AND &33) << 2) OR (bottom AND &33)
    """
    return mode1_byte([LOGICAL_COLOUR[c] for c in pattern])


def _byte_rows(values: list[int], per_row: int = 8) -> list[str]:
    return [
        "    EQUB " + ", ".join(f"&{v:02X}" for v in values[i:i + per_row])
        for i in range(0, len(values), per_row)
    ]


def generate(table: InkTable) -> str:
    lines: list[str] = []
    emit = lines.append

    emit("\\ " + "=" * 74)
    emit("\\ ink_tables.asm -- GENERATED by tools/dontdither/gen_tables.py")
    emit("\\ from data/ink_patterns.json. Do not edit; regenerate with `uv run dd-build`.")
    emit("\\")
    emit("\\ An ink state is the count tuple (C,M,Y,K), C+M+Y+K = 4, numbered 0..34 in")
    emit("\\ lexicographic order. Each state has one canonical 2x2 pattern of MODE 1")
    emit("\\ pixels. A superpixel occupies one half of each of two vertically adjacent")
    emit("\\ raster bytes: the left half (mask &CC) for even sx, the right half (mask")
    emit("\\ &33) for odd sx.")
    emit("\\")
    emit("\\ Logical colours: " + ", ".join(f"{i}={LOGICAL_COLOUR[i]}" for i in "KCMY"))
    emit("\\ " + "=" * 74)
    emit("")

    emit("\\ Named constants for ink states used by the game code.")
    for name, state in (
        ("STATE_ALL_C", (4, 0, 0, 0)),
        ("STATE_ALL_M", (0, 4, 0, 0)),
        ("STATE_ALL_Y", (0, 0, 4, 0)),
        ("STATE_ALL_K", (0, 0, 0, 4)),
        ("STATE_FOUR_WAY", (1, 1, 1, 1)),   # four-player initial arena fill
        ("STATE_CHECKER_CM", (2, 2, 0, 0)),  # two-player initial arena fill
    ):
        emit(f"{name:<18} = {table.states.index(state):2d}    \\ {state} {table.pattern(state)}")
    emit(f"STATE_COUNT        = {len(table.states)}")
    emit(f"NON_CANONICAL      = &{NON_CANONICAL:02X}  \\ pattern_to_state entry for a non-ink arrangement")
    emit("")

    lookup = [NON_CANONICAL] * 256
    for i, p in enumerate(table.patterns):
        lookup[superpixel_index(p)] = i
    emit("\\ pattern_to_state: 256 entries, page-aligned so it can be indexed with a")
    emit("\\ single absolute,X/Y access and no page-crossing penalty. It comes first")
    emit("\\ so that, INCLUDEd at the start of a page, it needs no padding.")
    emit("\\ Index: a MODE 1 byte whose four pixels (left to right) are TL, TR, BL, BR")
    emit("\\ of the superpixel, formed from the top and bottom raster bytes as")
    emit("\\     even sx:  (top AND &CC) OR ((bottom AND &CC) >> 2)")
    emit("\\     odd sx:   ((top AND &33) << 2) OR (bottom AND &33)")
    emit(f"\\ Entry: ink state 0..34, or NON_CANONICAL (&{NON_CANONICAL:02X}).")
    emit("ALIGN &100")
    emit(".pattern_to_state")
    lines.extend(_byte_rows(lookup, per_row=16))
    emit("")
    emit("\\ VDU 19 palette setup: logical colour, physical colour for each ink.")
    emit("\\ Four records of six VDU bytes: 19, logical, physical, 0, 0, 0.")
    emit(".palette_vdu_bytes")
    for ink in "KCMY":
        emit(f"    EQUB 19, {LOGICAL_COLOUR[ink]}, {PHYSICAL_COLOUR[ink]}, 0, 0, 0"
             f"    \\ logical {LOGICAL_COLOUR[ink]} = {ink}")
    emit(".palette_vdu_bytes_end")
    emit("")

    tops, bottoms = zip(*(pattern_rows_as_mode1_bytes(p) for p in table.patterns))
    emit("\\ state_top_bytes / state_bottom_bytes: indexed by state 0..34.")
    emit("\\ Each is a full screen byte holding the state's top (or bottom) pixel row")
    emit("\\ in BOTH halves, i.e. two identical superpixels side by side. AND with &CC")
    emit("\\ or &33 to take the half belonging to an even or odd superpixel column.")
    emit(".state_top_bytes")
    for i, (s, p, v) in enumerate(zip(table.states, table.patterns, tops)):
        emit(f"    EQUB &{v:02X}    \\ {i:2d} {s} {p[:2]}/{p[2:]} top row {p[:2]}")
    emit(".state_bottom_bytes")
    for i, (s, p, v) in enumerate(zip(table.states, table.patterns, bottoms)):
        emit(f"    EQUB &{v:02X}    \\ {i:2d} {s} {p[:2]}/{p[2:]} bottom row {p[2:]}")
    emit("")

    emit(f"\\ Ink order in state tuples: {', '.join(INKS)}")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Screen geometry tables
# ---------------------------------------------------------------------------

def generate_screen_tables() -> str:
    lines = [
        "\\ " + "=" * 74,
        "\\ screen_tables.asm -- GENERATED by tools/dontdither/gen_tables.py.",
        "\\ Do not edit; regenerate with `uv run dd-build`.",
        "\\ " + "=" * 74,
        "",
        "\\ (The superpixel row address tables are not generated: they are simple",
        "\\ enough to build at start-up, by build_superpixel_rows in arena.asm, into",
        "\\ uninitialised memory.)",
        "",
        "\\ bit_masks: bit_masks?n selects bit (7 - n); used to test column n of a",
        "\\ bitmap byte whose most significant bit is the leftmost cell.",
        ".bit_masks",
        "    EQUB &80, &40, &20, &10, &08, &04, &02, &01",
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Wall tiles
# ---------------------------------------------------------------------------

def generate_wall_tiles() -> str:
    from dontdither.walls import (
        CORNERS,
        EAST,
        NORTH,
        SOUTH,
        WEST,
        Colouring,
        full_byte,
        tile_inks,
        tile_rim_mask,
    )

    names = {NORTH: "N", EAST: "E", SOUTH: "S", WEST: "W"}
    lines = [
        "\\ " + "=" * 74,
        "\\ wall_tiles.asm -- GENERATED by tools/dontdither/gen_tables.py.",
        "\\ Do not edit; regenerate with `uv run dd-build`.",
        "\\",
        "\\ Walls occupy whole MODE 1 character cells (8x8 pixels = 4x4",
        "\\ superpixels). Each tile has a solid core and a one-pixel rim on every",
        "\\ side that does not join a neighbouring wall. The (core, rim) inks are",
        "\\ chosen per level and must differ. Tiles are stored as rim masks (rim",
        "\\ pixels all ones, core pixels zero); the screen byte for mask byte m is",
        "\\     core EOR ((core EOR rim) AND m)",
        "\\ " + "=" * 74,
        "",
        "\\ Neighbour mask bits, combined to index wall_tiles.",
        f"WALL_NORTH = {NORTH}",
        f"WALL_EAST  = {EAST}",
        f"WALL_SOUTH = {SOUTH}",
        f"WALL_WEST  = {WEST}",
        "",
        "\\ Wall inks: a screen byte of four pixels in each ink, for zp_wall_core",
        "\\ and zp_wall_rim.",
    ]
    for ink in "KCMY":
        lines.append(f"WALL_INK_{ink} = &{full_byte(ink):02X}")
    lines += [
        "",
        "\\ wall_corners: inner-corner patches, four records of five bytes:",
        "\\   arms     neighbour mask bits that must both be set",
        "\\   dx, dy   offset of the diagonal neighbour (two's complement)",
        "\\   offset   byte within the tile (0-7 left column, 8-15 right column)",
        "\\   pixel    pixel mask within that byte",
        "\\ If both arms join and the diagonal cell is not a wall, the corner pixel",
        "\\ is set to the rim ink so the outline of the inner corner is continuous.",
        ".wall_corners",
    ]
    for arms, (dx, dy), offset, pixel_mask in CORNERS:
        arm_names = "+".join(names[b] for b in (NORTH, EAST, SOUTH, WEST) if arms & b)
        lines.append(f"    EQUB {arms}, {dx & 0xFF}, {dy & 0xFF}, {offset}, &{pixel_mask:02X}"
                     f"    \\ {arm_names} corner")
    lines += [
        "WALL_CORNER_RECORD = 5",
        "WALL_CORNER_COUNT  = 4",
        "",
        "\\ wall_tiles: 16 rim masks of 16 bytes, indexed by neighbour mask * 16.",
        "\\ Each is in screen order: the left byte column's 8 raster lines, then",
        "\\ the right byte column's, so it maps straight onto a character cell.",
        "\\ In the pictures, R is rim and . is core.",
        ".wall_tiles",
    ]
    for mask in range(16):
        joined = "".join(names[b] for b in (NORTH, EAST, SOUTH, WEST) if mask & b) or "none"
        inks = tile_inks(mask, Colouring(core="K", rim="C"))
        lines.append(f"    \\ mask {mask:2d}: joins {joined}")
        for y in range(8):
            lines.append("    \\   " + "".join("." if c == "K" else "R" for c in inks[y]))
        lines += _byte_rows(list(tile_rim_mask(mask)), per_row=8)
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Test card layout
# ---------------------------------------------------------------------------

def generate_testcard_data(table: InkTable) -> str:
    from dontdither.screen import ARENA_CELLS
    from dontdither.testcard import (
        BORDER_COLOURING,
        SWATCH_CELLS,
        SWATCH_COLUMNS,
        swatch_colouring,
        swatch_index_of_superpixel,
        swatch_origin_cell,
        swatch_states,
        wall_cells,
    )
    from dontdither.walls import wall_bitmap

    states = swatch_states()
    columns = [swatch_index_of_superpixel(c) for c in range(ARENA_CELLS)]
    lines = [
        "\\ " + "=" * 74,
        "\\ testcard_data.asm -- GENERATED by tools/dontdither/gen_tables.py from",
        "\\ tools/dontdither/testcard.py. Do not edit; regenerate with `uv run dd-build`.",
        "\\ " + "=" * 74,
        "",
        "\\ testcard_swatch_states: ink state of each of the 6x6 swatches, row-major.",
        ".testcard_swatch_states",
    ]
    for row in range(len(states) // SWATCH_COLUMNS):
        chunk = states[row * SWATCH_COLUMNS:(row + 1) * SWATCH_COLUMNS]
        lines.append("    EQUB " + ", ".join(f"{table.states.index(s):2d}" for s in chunk)
                     + "    \\ " + " ".join("".join(map(str, s)) for s in chunk))
    lines += [
        "",
        "\\ testcard_swatch_column: swatch column (0..5) of superpixel column sx.",
        ".testcard_swatch_column",
        *_byte_rows(columns, per_row=16),
        "",
        "\\ testcard_swatch_row_base: first swatch index (row * 6) of the swatch row",
        "\\ containing superpixel row sy.",
        ".testcard_swatch_row_base",
        *_byte_rows([c * SWATCH_COLUMNS for c in columns], per_row=16),
        "",
        f"TESTCARD_BORDER_CORE = WALL_INK_{BORDER_COLOURING.core}   \\ border wall colouring",
        f"TESTCARD_BORDER_RIM  = WALL_INK_{BORDER_COLOURING.rim}",
        f"TESTCARD_SWATCH_CELLS = {SWATCH_CELLS}   \\ character cells per swatch side",
        "",
        "\\ testcard_swatch_walls: per swatch, 4 bytes: origin cell cx, cy (top-left",
        "\\ of the 5x5-cell swatch), then core and rim ink bytes for its feature.",
        "\\ The 12 (core, rim) colourings repeat three times over the 36 swatches.",
        ".testcard_swatch_walls",
        *(
            f"    EQUB {cx:2d}, {cy:2d}, WALL_INK_{c.core}, WALL_INK_{c.rim}    \\ swatch {i:2d}: {c.core} core, {c.rim} rim"
            for i in range(len(states))
            for (cx, cy), c in [(swatch_origin_cell(i), swatch_colouring(i))]
        ),
        "TESTCARD_SWATCH_RECORD = 4",
        f"TESTCARD_SWATCH_COUNT  = {len(states)}",
        "",
        "\\ testcard_walls: 32x32 wall bitmap, 4 bytes per character row, most",
        "\\ significant bit = leftmost cell.",
        ".testcard_walls",
        *_byte_rows(list(wall_bitmap(wall_cells())), per_row=4),
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Levels
# ---------------------------------------------------------------------------

MAX_LEVELS = 16                # per level set
LEVEL_TEMP = 0x6000            # where the loader loads a level set before copying it


def generate_level_format() -> str:
    """Definitions shared by the game and the level-set files."""
    from dontdither.levels import LevelOp

    return "\n".join([
        "\\ " + "=" * 74,
        "\\ level_format.asm -- GENERATED by tools/dontdither/gen_tables.py.",
        "\\ Do not edit; regenerate with `uv run dd-build`. Included by the game and",
        "\\ by each level-set file (LEVELS2, LEVELS4).",
        "\\",
        "\\ A level set is loaded into the game's level area. It begins with a",
        "\\ fixed header, then the levels' bytecode and titles:",
        "\\   +0                   players in this set's levels (2 or 4)",
        "\\   +1                   number of levels",
        "\\   +2                   bytecode addresses, low bytes  (MAX_LEVELS)",
        "\\   +2 + MAX_LEVELS      bytecode addresses, high bytes (MAX_LEVELS)",
        "\\   +2 + 2 * MAX_LEVELS  title addresses, low bytes     (MAX_LEVELS)",
        "\\   +2 + 3 * MAX_LEVELS  title addresses, high bytes    (MAX_LEVELS)",
        "\\ A title is a length byte then that many characters. A level's",
        "\\ bytecode (see asm/level.asm) is a header of symmetry step (1 ROT4, 2",
        "\\ ROT2), wall core and rim ink bytes and fill state, then commands.",
        "\\ " + "=" * 74,
        "",
        f"MAX_LEVELS = {MAX_LEVELS}",
        f"LEVEL_TEMP = &{LEVEL_TEMP:04X}   \\ where the loader loads a level set",
        "",
        "LEVEL_SET_PLAYERS = 0",
        "LEVEL_SET_COUNT   = 1",
        "LEVEL_SET_CODE_LO = 2",
        "LEVEL_SET_CODE_HI = 2 + MAX_LEVELS",
        "LEVEL_SET_NAME_LO = 2 + 2 * MAX_LEVELS",
        "LEVEL_SET_NAME_HI = 2 + 3 * MAX_LEVELS",
        "",
        "\\ Opcodes",
        *(f"LEVEL_{op.name:<6}= {op.value}" for op in LevelOp),
        "",
        "\\ Level bytecode header offsets",
        "LEVEL_HEADER_SYMMETRY = 0   \\ quarter turns between copies: 1 ROT4, 2 ROT2",
        "LEVEL_HEADER_CORE     = 1   \\ wall core ink byte",
        "LEVEL_HEADER_RIM      = 2   \\ wall rim ink byte",
        "LEVEL_HEADER_FILL     = 3   \\ ink state of open cells",
        "LEVEL_HEADER_SIZE     = 4",
        "LEVEL_START_SX        = LEVEL_HEADER_SIZE + 1   \\ the START command follows",
        "LEVEL_START_SY        = LEVEL_HEADER_SIZE + 2   \\ the header",
        "LEVEL_START_FACING    = LEVEL_HEADER_SIZE + 3",
    ]) + "\n"


def generate_level_set(table: InkTable, players: int, level_area: int) -> str:
    """Source for a level-set file: assembled at the game's level area and
    saved to load at LEVEL_TEMP, from where the loader copies it."""
    from dontdither.levels import FACINGS, level_filepaths, parse_level

    pairs = [(p, parse_level(p.read_text(), p.name)) for p in level_filepaths()]
    pairs = [(p, lv) for p, lv in pairs if lv.symmetry.copies == players]
    if not 0 < len(pairs) <= MAX_LEVELS:
        raise ValueError(f"The {players}-player set has {len(pairs)} levels; it needs 1..{MAX_LEVELS}")
    count = len(pairs)
    pad = MAX_LEVELS - count
    lines = [
        "\\ " + "=" * 74,
        f"\\ levels{players}.asm -- GENERATED by tools/dontdither/gen_tables.py from the",
        f"\\ {players}-player levels in levels/*.lvl. Do not edit; regenerate with",
        "\\ `uv run dd-build`. See level_format.asm for the layout.",
        "\\ " + "=" * 74,
        "",
        'INCLUDE "build/generated/level_format.asm"',
        'INCLUDE "build/generated/wall_ink_bytes.asm"',
        "",
        f"ORG &{level_area:04X}          \\ the game's level area",
        "GUARD &3000",
        ".level_set_start",
        f"    EQUB {players}, {count}",
        "    EQUB " + ", ".join([f"LO(level_{i})" for i in range(count)] + ["0"] * pad),
        "    EQUB " + ", ".join([f"HI(level_{i})" for i in range(count)] + ["0"] * pad),
        "    EQUB " + ", ".join([f"LO(level_name_{i})" for i in range(count)] + ["0"] * pad),
        "    EQUB " + ", ".join([f"HI(level_name_{i})" for i in range(count)] + ["0"] * pad),
    ]
    for i, (filepath, lv) in enumerate(pairs):
        code = lv.bytecode(table)
        if len(code) > 255:
            raise ValueError(f"{filepath.name}: bytecode is {len(code)} bytes; the limit is 255")
        lines += [
            "",
            f"\\ ---- Level {i + 1}: {lv.name} ({filepath.name}) ----",
            f".level_name_{i}",
            f"    EQUB {len(lv.name)}",
            f'    EQUS "{lv.name}"',
            f".level_{i}",
            f"    EQUB {lv.symmetry.value}    \\ {lv.symmetry.name}",
            f"    EQUB WALL_INK_{lv.colouring.core}, WALL_INK_{lv.colouring.rim}"
            f"    \\ walls: {lv.colouring.core} core, {lv.colouring.rim} rim",
            f"    EQUB {table.states.index(lv.fill)}    \\ fill state {lv.fill}",
            f"    EQUB LEVEL_START, {lv.start.sx}, {lv.start.sy}, {lv.start.facing}"
            f"    \\ player 1 at ({lv.start.sx}, {lv.start.sy}) facing {FACINGS[lv.start.facing]}",
        ]
        for op, x, y in lv.commands:
            lines.append(f"    EQUB LEVEL_{op.name}, {x}, {y}")
        lines.append("    EQUB LEVEL_END")
    lines += [
        ".level_set_end",
        "",
        f'SAVE "LEVELS{players}", level_set_start, level_set_end, level_set_start, LEVEL_TEMP',
    ]
    return "\n".join(lines) + "\n"


def generate_wall_ink_bytes() -> str:
    from dontdither.walls import full_byte

    return "\n".join(f"WALL_INK_{ink} = &{full_byte(ink):02X}" for ink in "KCMY") + "\n"


# ---------------------------------------------------------------------------
# Player sprites
# ---------------------------------------------------------------------------

def generate_sprite_data() -> str:
    from dontdither.sprites import (
        CONTRAST_INK,
        FACINGS,
        FRAME_BYTES,
        footprint_mask_plane,
        frame_order,
        frame_planes,
        load_tank,
    )
    from dontdither.walls import full_byte

    tank = load_tank()
    lines = [
        "\\ " + "=" * 74,
        "\\ sprite_data.asm -- GENERATED by tools/dontdither/gen_tables.py from",
        "\\ sprites/tank.spr. Do not edit; regenerate with `uv run dd-build`.",
        "\\",
        "\\ One frame per facing (0 = N, clockwise) and alignment (0: even sx, sprite",
        "\\ starts at the left of a byte; 1: odd sx, 2 pixels in). Frame number =",
        "\\ facing * 2 + alignment. Each frame is SPRITE_FRAME_BYTES mask bytes and as",
        "\\ many select bytes, in drawing order: per superpixel row, the top raster",
        "\\ line's 4 bytes then the bottom line's. Mask pixels are ones where the",
        "\\ sprite is opaque; select pixels are ones where it shows the player's ink",
        "\\ (elsewhere the contrast ink).",
        "\\ " + "=" * 74,
        "",
        f"SPRITE_FRAME_BYTES = {FRAME_BYTES}",
        "SPRITE_FOOTPRINT   = 6      \\ superpixels per side",
        "",
        "\\ sprite_line_offsets: for frame byte i, the offset of its screen byte",
        "\\ from the address of the top raster line of its superpixel row:",
        "\\ byte * 8 + raster line within the row (0 top, 1 bottom).",
        ".sprite_line_offsets",
        *_byte_rows([byte * 8 + line % 2 for line, byte in frame_order()], per_row=8),
        "",
        "\\ Player ink and contrast ink bytes, indexed by ink (0 = C .. 3 = K).",
        ".ink_bytes",
        "    EQUB " + ", ".join(f"&{full_byte(i):02X}" for i in "CMYK") + "    \\ C, M, Y, K",
        ".contrast_ink_bytes",
        "    EQUB " + ", ".join(f"&{full_byte(CONTRAST_INK[i]):02X}" for i in "CMYK")
        + "    \\ " + ", ".join(CONTRAST_INK[i] for i in "CMYK"),
        "",
        "\\ footprint_mask_0 / _1: for each frame byte, ones on the pixels inside",
        "\\ the 6x6-superpixel footprint, for even (0) and odd (1) alignment. A",
        "\\ tank owns exactly these bits: restoring its background touches only",
        "\\ them, so tanks side by side sharing a byte column cannot disturb",
        "\\ each other.",
        ".footprint_mask_0",
        *_byte_rows(list(footprint_mask_plane(0)), per_row=8),
        ".footprint_mask_1",
        *_byte_rows(list(footprint_mask_plane(1)), per_row=8),
        "",
        "\\ Frame addresses, indexed by frame number.",
        ".sprite_mask_lo",
        *(f"    EQUB LO(sprite_mask_{n})" for n in range(16)),
        ".sprite_mask_hi",
        *(f"    EQUB HI(sprite_mask_{n})" for n in range(16)),
        ".sprite_select_lo",
        *(f"    EQUB LO(sprite_select_{n})" for n in range(16)),
        ".sprite_select_hi",
        *(f"    EQUB HI(sprite_select_{n})" for n in range(16)),
    ]
    for facing_number, facing in enumerate(FACINGS):
        for alignment in range(2):
            n = facing_number * 2 + alignment
            mask, select = frame_planes(tank[facing], alignment)
            lines += [
                "",
                f"\\ Frame {n}: facing {facing}, {'odd' if alignment else 'even'} sx",
                f".sprite_mask_{n}",
                *_byte_rows(list(mask), per_row=8),
                f".sprite_select_{n}",
                *_byte_rows(list(select), per_row=8),
            ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Game constants: input, controls and movement
# ---------------------------------------------------------------------------

def generate_game_data() -> str:
    from dontdither import ai
    from dontdither.controls import LAYOUT_KEYS, LAYOUTS, inkey_code
    from dontdither.game import (
        DEMO_ROUND_TICKS,
        FIRING_GROUND,
        GROUND_AXIAL_SPEED,
        GROUND_DIAGONAL_SPEED,
        GROUND_LEVELS,
        GROUND_REFILL,
        RESERVOIR_SPLATS,
        ROUND_TICKS,
        SELECT_SECONDS,
        TICKS_PER_SECOND,
        DIRECTION_DX,
        DIRECTION_DY,
        FIRE_BIT,
        MAX_POSITION,
        NO_DIRECTION,
        direction_of_keys,
    )

    lines = [
        "\\ " + "=" * 74,
        "\\ game_data.asm -- GENERATED by tools/dontdither/gen_tables.py from",
        "\\ tools/dontdither/game.py and controls.py. Do not edit; regenerate with",
        "\\ `uv run dd-build`.",
        "\\ " + "=" * 74,
        "",
        "\\ Player input byte: direction 0..7 (0 = N, clockwise) or NO_DIRECTION in",
        "\\ the low nibble, plus FIRE_BIT.",
        f"NO_DIRECTION   = &{NO_DIRECTION:02X}",
        "DIRECTION_MASK = &0F",
        f"FIRE_BIT       = &{FIRE_BIT:02X}",
        "",
        f"MAX_POSITION   = {MAX_POSITION}   \\ largest sx or sy keeping the footprint in the arena",
        "",
        "\\ Rounds.",
        f"TICKS_PER_SECOND = {TICKS_PER_SECOND}",
        f"ROUND_TICKS      = {ROUND_TICKS}   \\ default round length ({ROUND_TICKS // TICKS_PER_SECOND} s)",
        f"DEMO_ROUND_TICKS = {DEMO_ROUND_TICKS}   \\ demo mode rounds ({DEMO_ROUND_TICKS // TICKS_PER_SECOND} s)",
        f"SELECT_SECONDS   = {SELECT_SECONDS}   \\ time to join before a session",
        "",
        "\\ Player control sources.",
        "CONTROL_NONE     = 0   \\ no input (stationary)",
        "CONTROL_KEYS     = 1   \\ the keyboard: the slot's own layout in key_layouts",
        "CONTROL_JOYSTICK = 2   \\ reserved: a joystick, for a player who joins with its",
        "                       \\ fire button (Beebium cannot emulate one yet)",
        "CONTROL_SCRIPTED = 3   \\ player_input written by someone else (tests)",
        "CONTROL_AI       = 4   \\ the computer (ai.asm)",
        "",
        "\\ AI (see tools/dontdither/ai.py).",
        f"AI_PERIOD      = {ai.AI_PERIOD}   \\ ticks between decisions (a power of two)",
        f"AI_PERSISTENCE = {ai.PERSISTENCE}   \\ bonus for keeping the current direction",
        f"AI_FIRE_SCORE  = {ai.FIRE_SCORE}  \\ fire when the chosen direction scores this",
        f"AI_WALL_VALUE  = {ai.WALL_VALUE}   \\ worth of a wall or off-arena sample",
        f"AI_SAMPLES     = {len(ai.SAMPLES_E)}   \\ samples per direction",
        f"AI_REFILL_BASE = {ai.REFILL_BASE}   \\ refilling, a cell is worth this + own count",
        f"AI_REFILLED    = {ai.REFILLED}  \\ splats at which a refilling AI paints again",
        "\\ ai_samples: sample cells (dx, dy from the footprint's top-left, two's",
        "\\ complement) for facing E, then for NE; rotated for other facings.",
        ".ai_samples",
        "    EQUB " + ", ".join(f"&{v & 0xFF:02X}" for c in ai.SAMPLES_E for v in c) + "    \\ E",
        "    EQUB " + ", ".join(f"&{v & 0xFF:02X}" for c in ai.SAMPLES_NE for v in c) + "    \\ NE",
        "",
        "\\ Step per direction, as two's complement bytes (-1 = &FF).",
        ".direction_dx",
        "    EQUB " + ", ".join(f"&{d & 0xFF:02X}" for d in DIRECTION_DX) + "    \\ N NE E SE S SW W NW",
        ".direction_dy",
        "    EQUB " + ", ".join(f"&{d & 0xFF:02X}" for d in DIRECTION_DY),
        "",
        "\\ The ink reservoir and the ground (see game.py). A tank's ground level",
        "\\ (0..4) is its own ink quanta over the centre four superpixels of its",
        "\\ footprint, DIV 4; FIRING_GROUND applies while fire is held.",
        f"RESERVOIR_SPLATS = {RESERVOIR_SPLATS}   \\ a full reservoir",
        f"GROUND_LEVELS    = {GROUND_LEVELS}",
        f"FIRING_GROUND    = {FIRING_GROUND}",
        "\\ Speed by ground level, in 1/256 superpixel per tick, indexed by",
        "\\ ground * 2 + (direction AND 1): axial, then diagonal (axial / sqrt 2).",
        "\\ The low byte is added to an 8-bit accumulator; the carry plus the",
        "\\ whole part is the number of steps this tick (0..2).",
        ".ground_speed_lo",
        "    EQUB " + ", ".join(f"{speed & 0xFF}" for g in range(GROUND_LEVELS)
                            for speed in (GROUND_AXIAL_SPEED[g], GROUND_DIAGONAL_SPEED[g])),
        ".ground_speed_whole",
        "    EQUB " + ", ".join(f"{speed >> 8}" for g in range(GROUND_LEVELS)
                            for speed in (GROUND_AXIAL_SPEED[g], GROUND_DIAGONAL_SPEED[g])),
        "\\ Refill by ground level, in 1/256 splat per tick, while fire is released.",
        ".ground_refill",
        "    EQUB " + ", ".join(str(r) for r in GROUND_REFILL),
        "",
        "\\ key_direction: direction for a 4-bit mask of held keys (bit 0 up,",
        "\\ 1 down, 2 left, 3 right). Opposite keys cancel.",
        ".key_direction",
        "    EQUB " + ", ".join(f"&{direction_of_keys(m):02X}" for m in range(16)),
        "",
        "\\ Keyboard layouts: KEY_LAYOUT_BYTES negative-INKEY codes per player slot,",
        "\\ in key_layouts -- the block SPLASH leaves resident (asm/handoff.asm).",
        f"KEY_LAYOUT_BYTES = {len(LAYOUT_KEYS)}",
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Painting: ink state arithmetic and splat trees
# ---------------------------------------------------------------------------

NO_PARENT = 0x7F
PAINTS_FLAG = 0x80


def generate_paint_data(table: InkTable) -> str:
    from dontdither.game import FIRE_PERIOD
    from dontdither.splats import SPLATS_FILEPATH, parse_splats, ray_tree

    splats = parse_splats(SPLATS_FILEPATH.read_text(), SPLATS_FILEPATH.name)
    variants = len(splats["E"])
    trees = [(base, v, ray_tree(splats[base][v])) for base in ("E", "NE") for v in range(variants)]
    max_nodes = max(len(t) for _, _, t in trees)

    state_of_counts = [0xFF] * 125
    for i, (c, m, y, k) in enumerate(table.states):
        state_of_counts[c * 25 + m * 5 + y] = i

    lines = [
        "\\ " + "=" * 74,
        "\\ paint_data.asm -- GENERATED by tools/dontdither/gen_tables.py from",
        "\\ tools/dontdither/game.py, the ink table and sprites/splats.spr. Do not",
        "\\ edit; regenerate with `uv run dd-build`.",
        "\\ " + "=" * 74,
        "",
        f"FIRE_PERIOD    = {FIRE_PERIOD}   \\ ticks between shots while fire is held",
        f"SPLAT_VARIANTS = {variants}   \\ variants per facing, cycled per shot",
        f"SPLAT_MAX_NODES = {max_nodes}  \\ most nodes in any splat tree",
        "",
        "\\ state_counts: the ink counts of each state, 4 bytes per state in the",
        "\\ order C, M, Y, K. Index = state * 4 + ink.",
        ".state_counts",
        *(f"    EQUB {c}, {m}, {y}, {k}    \\ {i:2d}" for i, (c, m, y, k) in enumerate(table.states)),
        "",
        "\\ state_index_of: for each state, C * 25 + M * 5 + Y, its index into",
        "\\ state_of_counts. Moving one quantum from ink v to ink p changes the",
        "\\ index by ink_weight[p] - ink_weight[v].",
        ".state_index_of",
        *_byte_rows([c * 25 + m * 5 + y for c, m, y, k in table.states], per_row=16),
        ".ink_weight",
        "    EQUB 25, 5, 1, 0    \\ C, M, Y, K",
        "",
        "\\ state_of_counts: the state with counts (C, M, Y, K), indexed by",
        "\\ C * 25 + M * 5 + Y (K is 4 - C - M - Y). Unused entries are &FF.",
        ".state_of_counts",
        *_byte_rows(state_of_counts, per_row=25),
        "",
        "\\ Splat trees (see tools/dontdither/splats.py): the cells on the lines",
        "\\ from the tank's footprint centre to each splat cell, parents before",
        "\\ children. Three bytes per node:",
        "\\   dx, dy   cell offset from the footprint's top-left superpixel, two's",
        "\\            complement, for facing E (tree 0..) or NE (tree SPLAT_VARIANTS..);",
        "\\            other facings rotate it: (x, y) -> (5 - y, x) per quarter turn",
        f"\\   parent   index of the parent node, or &{NO_PARENT:02X} for none; bit 7 set",
        "\\            if the node is a splat cell to paint (else only passed over)",
        "\\ A node is blocked if its cell is a wall or outside the arena, or its",
        "\\ parent is blocked; unblocked splat cells are painted.",
        f"SPLAT_NO_PARENT = &{NO_PARENT:02X}",
        f"SPLAT_PAINTS    = &{PAINTS_FLAG:02X}",
        "SPLAT_NODE_BYTES = 3",
        ".splat_tree_lo",
        *(f"    EQUB LO(splat_tree_{i})" for i in range(len(trees))),
        ".splat_tree_hi",
        *(f"    EQUB HI(splat_tree_{i})" for i in range(len(trees))),
        ".splat_tree_nodes",
        "    EQUB " + ", ".join(str(len(t)) for _, _, t in trees),
    ]
    for i, (base, v, tree) in enumerate(trees):
        lines += ["", f"\\ Tree {i}: facing {base}, variant {v + 1}", f".splat_tree_{i}"]
        for n, node in enumerate(tree):
            dx, dy = node.cell
            parent = NO_PARENT if node.parent < 0 else node.parent
            flag = PAINTS_FLAG if node.paints else 0
            lines.append(f"    EQUB &{dx & 0xFF:02X}, &{dy & 0xFF:02X}, &{parent | flag:02X}"
                         f"    \\ {n:2d}: ({dx:3d}, {dy:3d}) parent {node.parent:3d}{' paint' if node.paints else ''}")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# HUD font
# ---------------------------------------------------------------------------

def generate_hud_font() -> str:
    from dontdither.hud_font import DIGITS, GLYPH_ROWS, glyph_bytes

    lines = [
        "\\ " + "=" * 74,
        "\\ hud_font.asm -- GENERATED by tools/dontdither/gen_tables.py from",
        "\\ tools/dontdither/hud_font.py. Do not edit; regenerate with `uv run dd-build`.",
        "\\",
        "\\ A 3x5 digit font: GLYPH_ROWS bytes per digit, each one MODE 1 byte of",
        "\\ four pixels (three for the glyph, one gap) with all-ones pixels where",
        "\\ the glyph is set. AND with a colour byte to draw it in that colour.",
        "\\ " + "=" * 74,
        "",
        f"GLYPH_ROWS = {GLYPH_ROWS}",
        ".hud_digits",
    ]
    for digit in "0123456789":
        glyph = DIGITS[digit]
        lines.append("    EQUB " + ", ".join(f"&{b:02X}" for b in glyph_bytes(glyph))
                     + f"    \\ {digit}: " + " ".join(glyph))
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Splash screen
# ---------------------------------------------------------------------------

def key_layout_lines() -> list[str]:
    """The default key layouts (controls.py) as EQUB lines: per player slot,
    negative-INKEY codes (for OSBYTE &81) in the order fire, right, left,
    down, up -- the scan order, so that rotating each result into the key
    mask leaves up in bit 0 and fire in bit 4."""
    from dontdither.controls import LAYOUT_KEYS, LAYOUTS, inkey_code

    lines = []
    for name, layout in LAYOUTS.items():
        keys = [layout[k] for k in reversed(LAYOUT_KEYS)]
        lines.append("    EQUB " + ", ".join(f"&{inkey_code(k):02X}" for k in keys)
                     + f"    \\ {name}: " + ", ".join(keys))
    return lines


def key_name_lines() -> list[str]:
    """key_names: for every key, its negative-INKEY code then its name
    (controls.key_name), the last character with bit 7 set; then 0."""
    from dontdither.controls import INTERNAL_KEY, inkey_code, key_name

    lines = []
    for key in INTERNAL_KEY:
        name = key_name(key)
        chars = [ord(c) for c in name]
        chars[-1] |= 0x80
        lines.append(f"    EQUB &{inkey_code(key):02X}, " + ", ".join(f"&{c:02X}" for c in chars)
                     + f"    \\ {name}")
    lines.append("    EQUB 0                 \\ (No key's code is 0: that is INKEY -256.)")
    return lines


INK_NAMES = {"C": "Cyan", "M": "Magenta", "Y": "Yellow", "K": "Black"}


def key_line(ink: str) -> str:
    """How player `ink` plays: e.g. "Cyan: W A S D, SHIFT fires"."""
    from dontdither.controls import LAYOUTS

    layout = LAYOUTS[ink]
    return layout_line(ink, [layout[k] for k in ("up", "left", "down", "right", "fire")])


KEY_LINE_LENGTH = 35           # characters: from TEXT_COLUMN, short of column 39


def layout_line(ink: str, keys: list[str]) -> str:
    """How a player plays, given its keys up, left, down, right and fire:
    e.g. "Cyan: W A S D, SHIFT fires", or "cursor keys" for the four cursor
    keys. SPLASH prints it the same way from the resident layouts, cut off
    at KEY_LINE_LENGTH characters."""
    from dontdither.controls import key_name

    *directions, fire = keys
    if directions == ["UP", "LEFT", "DOWN", "RIGHT"]:
        moves = "cursor keys"
    else:
        moves = " ".join(key_name(k) for k in directions)
    return f"{INK_NAMES[ink]}: {moves}, {key_name(fire)} fires"[:KEY_LINE_LENGTH]


def generate_splash(dirpath) -> None:
    """The logo as screen bytes (logo.bin), a source that saves them as the
    disc file LOGO loading straight into screen memory, and the constants
    and palette the SPLASH program uses."""
    from dontdither.splash import LOGO_TOP_ROW, logo_band
    from dontdither.controls import LAYOUT_KEYS, inkey_code

    rows, band = logo_band()
    (dirpath / "logo.bin").write_bytes(band)
    (dirpath / "logo.asm").write_text("\n".join([
        "\\ logo.asm -- GENERATED by tools/dontdither/gen_tables.py from art/splash.png.",
        "\\ The logo's character rows of MODE 1 screen memory, saved as LOGO to load",
        "\\ straight into place.",
        f"ORG &3000 + {LOGO_TOP_ROW} * 640",
        ".logo_start",
        'INCBIN "build/generated/logo.bin"',
        ".logo_end",
        'SAVE "LOGO", logo_start, logo_end, logo_start',
    ]) + "\n")
    (dirpath / "splash_data.asm").write_text("\n".join([
        "\\ splash_data.asm -- GENERATED by tools/dontdither/gen_tables.py.",
        f"LOGO_TOP_ROW = {LOGO_TOP_ROW}",
        f"LOGO_ROWS    = {rows}",
        "\\ VDU 19 records mapping logical colours to the inks (as the game's).",
        ".splash_palette",
        *(f"    EQUB 19, {LOGICAL_COLOUR[ink]}, {PHYSICAL_COLOUR[ink]}, 0, 0, 0" for ink in "KCMY"),
        ".splash_palette_end",
        "\\ The default key layouts (controls.py), for key_layouts when the",
        "\\ resident block is not sealed (see asm/handoff.asm).",
        f"KEY_LAYOUT_BYTES = {len(LAYOUT_KEYS)}",
        ".default_key_layouts",
        *key_layout_lines(),
        "\\ key_names: every key's name, looked up by its negative-INKEY code.",
        ".key_names",
        *key_name_lines(),
        "\\ The players' names, each ending with bit 7 set, in slot order.",
        ".ink_names",
        *(f"    EQUB " + ", ".join(f"&{c:02X}" for c in [*map(ord, name[:-1]), ord(name[-1]) | 0x80])
          + f"    \\ {name}" for name in INK_NAMES.values()),
        f"KEY_LINE_LENGTH = {KEY_LINE_LENGTH}",
        "\\ The cursor keys' codes, as a layout holds its directions: up, left,",
        "\\ down, right. A layout of exactly these shows as \"cursor keys\".",
        ".cursor_key_codes",
        "    EQUB " + ", ".join(f"&{inkey_code(k):02X}" for k in ("UP", "LEFT", "DOWN", "RIGHT")),
    ]) + "\n")
    from dontdither.splash import HUD_FIRST_COLUMN, HUD_LOGO_ROWS, HUD_ROW_BYTES, hud_logo
    (dirpath / "hud_logo.bin").write_bytes(hud_logo())
    (dirpath / "hud_logo.asm").write_text("\n".join([
        "\\ hud_logo.asm -- GENERATED by tools/dontdither/gen_tables.py from art/splash.png.",
        "\\ The small logo at the top of the HUD: HUD_LOGO_ROWS character rows of",
        "\\ HUD_LOGO_ROW_BYTES bytes each (the HUD's byte columns of that row, which",
        "\\ are contiguous in screen memory), in hud_logo.bin. The DITHER loader",
        "\\ copies them into place; the game never draws over them.",
        f"HUD_LOGO_ROWS      = {HUD_LOGO_ROWS}",
        f"HUD_LOGO_ROW_BYTES = {HUD_ROW_BYTES}",
        f"HUD_LOGO_ADDRESS   = &3000 + {HUD_FIRST_COLUMN} * 8   \\ its first row's first byte",
    ]) + "\n")


def generate_all(dirpath) -> None:
    """Write every generated source file into dirpath."""
    table = InkTable.load()
    dirpath.mkdir(parents=True, exist_ok=True)
    (dirpath / "ink_tables.asm").write_text(generate(table))
    (dirpath / "screen_tables.asm").write_text(generate_screen_tables())
    (dirpath / "wall_tiles.asm").write_text(generate_wall_tiles())
    (dirpath / "testcard_data.asm").write_text(generate_testcard_data(table))
    (dirpath / "level_format.asm").write_text(generate_level_format())
    (dirpath / "wall_ink_bytes.asm").write_text(generate_wall_ink_bytes())
    (dirpath / "sprite_data.asm").write_text(generate_sprite_data())
    (dirpath / "game_data.asm").write_text(generate_game_data())
    (dirpath / "paint_data.asm").write_text(generate_paint_data(table))
    (dirpath / "hud_font.asm").write_text(generate_hud_font())
    generate_splash(dirpath)
