"""Generate beebasm source for the ink lookup tables from the canonical table."""

from __future__ import annotations

from dontdither.inks import (
    INKS,
    LOGICAL_COLOUR,
    PHYSICAL_COLOUR,
    InkTable,
    mode1_byte,
    pattern_rows_as_mode1_bytes,
)

# Marker in pattern_to_state for a 2x2 arrangement that is not a canonical ink.
NON_CANONICAL = 0xFF


def superpixel_index(pattern: str) -> int:
    """The pattern_to_state index of a literal 2x2 pattern.

    The index is itself a MODE 1 byte whose four pixels, left to right, are
    TL, TR, BL, BR. The 6502 forms it from the top and bottom raster bytes:
        even sx:  (top AND &CC) OR ((bottom AND &CC) >> 2)
        odd sx:   ((top AND &33) << 2) OR (bottom AND &33)
    """
    return mode1_byte([LOGICAL_COLOUR[c] for c in pattern])


def _byte_rows(values: list[int], per_row: int = 8) -> list[str]:
    return [
        "    EQUB " + ", ".join(f"&{v:02X}" for v in values[i:i + per_row])
        for i in range(0, len(values), per_row)
    ]


def generate(table: InkTable) -> str:
    lines: list[str] = []
    emit = lines.append

    emit("\\ " + "=" * 74)
    emit("\\ ink_tables.asm -- GENERATED by tools/dontdither/gen_tables.py")
    emit("\\ from data/ink_patterns.json. Do not edit; regenerate with `uv run dd-build`.")
    emit("\\")
    emit("\\ An ink state is the count tuple (C,M,Y,K), C+M+Y+K = 4, numbered 0..34 in")
    emit("\\ lexicographic order. Each state has one canonical 2x2 pattern of MODE 1")
    emit("\\ pixels. A superpixel occupies one half of each of two vertically adjacent")
    emit("\\ raster bytes: the left half (mask &CC) for even sx, the right half (mask")
    emit("\\ &33) for odd sx.")
    emit("\\")
    emit("\\ Logical colours: " + ", ".join(f"{i}={LOGICAL_COLOUR[i]}" for i in "KCMY"))
    emit("\\ " + "=" * 74)
    emit("")

    emit("\\ Named constants for ink states used by the game code.")
    for name, state in (
        ("STATE_ALL_C", (4, 0, 0, 0)),
        ("STATE_ALL_M", (0, 4, 0, 0)),
        ("STATE_ALL_Y", (0, 0, 4, 0)),
        ("STATE_ALL_K", (0, 0, 0, 4)),
        ("STATE_FOUR_WAY", (1, 1, 1, 1)),   # four-player initial arena fill
        ("STATE_CHECKER_CM", (2, 2, 0, 0)),  # two-player initial arena fill
    ):
        emit(f"{name:<18} = {table.states.index(state):2d}    \\ {state} {table.pattern(state)}")
    emit(f"STATE_COUNT        = {len(table.states)}")
    emit(f"NON_CANONICAL      = &{NON_CANONICAL:02X}  \\ pattern_to_state entry for a non-ink arrangement")
    emit("")

    emit("\\ VDU 19 palette setup: logical colour, physical colour for each ink.")
    emit("\\ Four records of six VDU bytes: 19, logical, physical, 0, 0, 0.")
    emit(".palette_vdu_bytes")
    for ink in "KCMY":
        emit(f"    EQUB 19, {LOGICAL_COLOUR[ink]}, {PHYSICAL_COLOUR[ink]}, 0, 0, 0"
             f"    \\ logical {LOGICAL_COLOUR[ink]} = {ink}")
    emit(".palette_vdu_bytes_end")
    emit("")

    tops, bottoms = zip(*(pattern_rows_as_mode1_bytes(p) for p in table.patterns))
    emit("\\ state_top_bytes / state_bottom_bytes: indexed by state 0..34.")
    emit("\\ Each is a full screen byte holding the state's top (or bottom) pixel row")
    emit("\\ in BOTH halves, i.e. two identical superpixels side by side. AND with &CC")
    emit("\\ or &33 to take the half belonging to an even or odd superpixel column.")
    emit(".state_top_bytes")
    for i, (s, p, v) in enumerate(zip(table.states, table.patterns, tops)):
        emit(f"    EQUB &{v:02X}    \\ {i:2d} {s} {p[:2]}/{p[2:]} top row {p[:2]}")
    emit(".state_bottom_bytes")
    for i, (s, p, v) in enumerate(zip(table.states, table.patterns, bottoms)):
        emit(f"    EQUB &{v:02X}    \\ {i:2d} {s} {p[:2]}/{p[2:]} bottom row {p[2:]}")
    emit("")

    lookup = [NON_CANONICAL] * 256
    for i, p in enumerate(table.patterns):
        lookup[superpixel_index(p)] = i
    emit("\\ pattern_to_state: 256 entries, page-aligned so it can be indexed with a")
    emit("\\ single absolute,X/Y access and no page-crossing penalty.")
    emit("\\ Index: a MODE 1 byte whose four pixels (left to right) are TL, TR, BL, BR")
    emit("\\ of the superpixel, formed from the top and bottom raster bytes as")
    emit("\\     even sx:  (top AND &CC) OR ((bottom AND &CC) >> 2)")
    emit("\\     odd sx:   ((top AND &33) << 2) OR (bottom AND &33)")
    emit(f"\\ Entry: ink state 0..34, or NON_CANONICAL (&{NON_CANONICAL:02X}).")
    emit("ALIGN &100")
    emit(".pattern_to_state")
    lines.extend(_byte_rows(lookup, per_row=16))
    emit("")
    emit(f"\\ Ink order in state tuples: {', '.join(INKS)}")
    return "\n".join(lines) + "\n"
