"""Generate beebasm source for the ink lookup tables from the canonical table."""

from __future__ import annotations

from dontdither.inks import (
    INKS,
    LOGICAL_COLOUR,
    PHYSICAL_COLOUR,
    InkTable,
    mode1_byte,
    pattern_rows_as_mode1_bytes,
)

# Marker in pattern_to_state for a 2x2 arrangement that is not a canonical ink.
NON_CANONICAL = 0xFF


def superpixel_index(pattern: str) -> int:
    """The pattern_to_state index of a literal 2x2 pattern.

    The index is itself a MODE 1 byte whose four pixels, left to right, are
    TL, TR, BL, BR. The 6502 forms it from the top and bottom raster bytes:
        even sx:  (top AND &CC) OR ((bottom AND &CC) >> 2)
        odd sx:   ((top AND &33) << 2) OR (bottom AND &33)
    """
    return mode1_byte([LOGICAL_COLOUR[c] for c in pattern])


def _byte_rows(values: list[int], per_row: int = 8) -> list[str]:
    return [
        "    EQUB " + ", ".join(f"&{v:02X}" for v in values[i:i + per_row])
        for i in range(0, len(values), per_row)
    ]


def generate(table: InkTable) -> str:
    lines: list[str] = []
    emit = lines.append

    emit("\\ " + "=" * 74)
    emit("\\ ink_tables.asm -- GENERATED by tools/dontdither/gen_tables.py")
    emit("\\ from data/ink_patterns.json. Do not edit; regenerate with `uv run dd-build`.")
    emit("\\")
    emit("\\ An ink state is the count tuple (C,M,Y,K), C+M+Y+K = 4, numbered 0..34 in")
    emit("\\ lexicographic order. Each state has one canonical 2x2 pattern of MODE 1")
    emit("\\ pixels. A superpixel occupies one half of each of two vertically adjacent")
    emit("\\ raster bytes: the left half (mask &CC) for even sx, the right half (mask")
    emit("\\ &33) for odd sx.")
    emit("\\")
    emit("\\ Logical colours: " + ", ".join(f"{i}={LOGICAL_COLOUR[i]}" for i in "KCMY"))
    emit("\\ " + "=" * 74)
    emit("")

    emit("\\ Named constants for ink states used by the game code.")
    for name, state in (
        ("STATE_ALL_C", (4, 0, 0, 0)),
        ("STATE_ALL_M", (0, 4, 0, 0)),
        ("STATE_ALL_Y", (0, 0, 4, 0)),
        ("STATE_ALL_K", (0, 0, 0, 4)),
        ("STATE_FOUR_WAY", (1, 1, 1, 1)),   # four-player initial arena fill
        ("STATE_CHECKER_CM", (2, 2, 0, 0)),  # two-player initial arena fill
    ):
        emit(f"{name:<18} = {table.states.index(state):2d}    \\ {state} {table.pattern(state)}")
    emit(f"STATE_COUNT        = {len(table.states)}")
    emit(f"NON_CANONICAL      = &{NON_CANONICAL:02X}  \\ pattern_to_state entry for a non-ink arrangement")
    emit("")

    emit("\\ VDU 19 palette setup: logical colour, physical colour for each ink.")
    emit("\\ Four records of six VDU bytes: 19, logical, physical, 0, 0, 0.")
    emit(".palette_vdu_bytes")
    for ink in "KCMY":
        emit(f"    EQUB 19, {LOGICAL_COLOUR[ink]}, {PHYSICAL_COLOUR[ink]}, 0, 0, 0"
             f"    \\ logical {LOGICAL_COLOUR[ink]} = {ink}")
    emit(".palette_vdu_bytes_end")
    emit("")

    tops, bottoms = zip(*(pattern_rows_as_mode1_bytes(p) for p in table.patterns))
    emit("\\ state_top_bytes / state_bottom_bytes: indexed by state 0..34.")
    emit("\\ Each is a full screen byte holding the state's top (or bottom) pixel row")
    emit("\\ in BOTH halves, i.e. two identical superpixels side by side. AND with &CC")
    emit("\\ or &33 to take the half belonging to an even or odd superpixel column.")
    emit(".state_top_bytes")
    for i, (s, p, v) in enumerate(zip(table.states, table.patterns, tops)):
        emit(f"    EQUB &{v:02X}    \\ {i:2d} {s} {p[:2]}/{p[2:]} top row {p[:2]}")
    emit(".state_bottom_bytes")
    for i, (s, p, v) in enumerate(zip(table.states, table.patterns, bottoms)):
        emit(f"    EQUB &{v:02X}    \\ {i:2d} {s} {p[:2]}/{p[2:]} bottom row {p[2:]}")
    emit("")

    lookup = [NON_CANONICAL] * 256
    for i, p in enumerate(table.patterns):
        lookup[superpixel_index(p)] = i
    emit("\\ pattern_to_state: 256 entries, page-aligned so it can be indexed with a")
    emit("\\ single absolute,X/Y access and no page-crossing penalty.")
    emit("\\ Index: a MODE 1 byte whose four pixels (left to right) are TL, TR, BL, BR")
    emit("\\ of the superpixel, formed from the top and bottom raster bytes as")
    emit("\\     even sx:  (top AND &CC) OR ((bottom AND &CC) >> 2)")
    emit("\\     odd sx:   ((top AND &33) << 2) OR (bottom AND &33)")
    emit(f"\\ Entry: ink state 0..34, or NON_CANONICAL (&{NON_CANONICAL:02X}).")
    emit("ALIGN &100")
    emit(".pattern_to_state")
    lines.extend(_byte_rows(lookup, per_row=16))
    emit("")
    emit(f"\\ Ink order in state tuples: {', '.join(INKS)}")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Screen geometry tables
# ---------------------------------------------------------------------------

def generate_screen_tables() -> str:
    from dontdither.screen import ARENA_CELLS, superpixel_address

    addresses = [superpixel_address(0, sy) for sy in range(ARENA_CELLS)]
    lines = [
        "\\ " + "=" * 74,
        "\\ screen_tables.asm -- GENERATED by tools/dontdither/gen_tables.py.",
        "\\ Do not edit; regenerate with `uv run dd-build`.",
        "\\ " + "=" * 74,
        "",
        "\\ superpixel_row_lo / _hi: address of the top raster byte of superpixel",
        "\\ (0, sy), indexed by sy = 0..127:",
        "\\     &3000 + (sy DIV 4) * 640 + (sy AND 3) * 2",
        "\\ Superpixel (sx, sy) is at that address + (sx DIV 2) * 8; the bottom",
        "\\ raster byte is the next address. For a character row cy, entry 4*cy is",
        "\\ the address of the row's first character cell.",
        ".superpixel_row_lo",
        *_byte_rows([a & 0xFF for a in addresses], per_row=16),
        ".superpixel_row_hi",
        *_byte_rows([a >> 8 for a in addresses], per_row=16),
        "",
        "\\ bit_masks: bit_masks?n selects bit (7 - n); used to test column n of a",
        "\\ bitmap byte whose most significant bit is the leftmost cell.",
        ".bit_masks",
        "    EQUB &80, &40, &20, &10, &08, &04, &02, &01",
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Wall tiles
# ---------------------------------------------------------------------------

def generate_wall_tiles() -> str:
    from dontdither.walls import (
        CORNERS,
        EAST,
        NORTH,
        SOUTH,
        WEST,
        Colouring,
        full_byte,
        tile_inks,
        tile_rim_mask,
    )

    names = {NORTH: "N", EAST: "E", SOUTH: "S", WEST: "W"}
    lines = [
        "\\ " + "=" * 74,
        "\\ wall_tiles.asm -- GENERATED by tools/dontdither/gen_tables.py.",
        "\\ Do not edit; regenerate with `uv run dd-build`.",
        "\\",
        "\\ Walls occupy whole MODE 1 character cells (8x8 pixels = 4x4",
        "\\ superpixels). Each tile has a solid core and a one-pixel rim on every",
        "\\ side that does not join a neighbouring wall. The (core, rim) inks are",
        "\\ chosen per level and must differ. Tiles are stored as rim masks (rim",
        "\\ pixels all ones, core pixels zero); the screen byte for mask byte m is",
        "\\     core EOR ((core EOR rim) AND m)",
        "\\ " + "=" * 74,
        "",
        "\\ Neighbour mask bits, combined to index wall_tiles.",
        f"WALL_NORTH = {NORTH}",
        f"WALL_EAST  = {EAST}",
        f"WALL_SOUTH = {SOUTH}",
        f"WALL_WEST  = {WEST}",
        "",
        "\\ Wall inks: a screen byte of four pixels in each ink, for zp_wall_core",
        "\\ and zp_wall_rim.",
    ]
    for ink in "KCMY":
        lines.append(f"WALL_INK_{ink} = &{full_byte(ink):02X}")
    lines += [
        "",
        "\\ wall_corners: inner-corner patches, four records of five bytes:",
        "\\   arms     neighbour mask bits that must both be set",
        "\\   dx, dy   offset of the diagonal neighbour (two's complement)",
        "\\   offset   byte within the tile (0-7 left column, 8-15 right column)",
        "\\   pixel    pixel mask within that byte",
        "\\ If both arms join and the diagonal cell is not a wall, the corner pixel",
        "\\ is set to the rim ink so the outline of the inner corner is continuous.",
        ".wall_corners",
    ]
    for arms, (dx, dy), offset, pixel_mask in CORNERS:
        arm_names = "+".join(names[b] for b in (NORTH, EAST, SOUTH, WEST) if arms & b)
        lines.append(f"    EQUB {arms}, {dx & 0xFF}, {dy & 0xFF}, {offset}, &{pixel_mask:02X}"
                     f"    \\ {arm_names} corner")
    lines += [
        "WALL_CORNER_RECORD = 5",
        "WALL_CORNER_COUNT  = 4",
        "",
        "\\ wall_tiles: 16 rim masks of 16 bytes, indexed by neighbour mask * 16.",
        "\\ Each is in screen order: the left byte column's 8 raster lines, then",
        "\\ the right byte column's, so it maps straight onto a character cell.",
        "\\ In the pictures, R is rim and . is core.",
        ".wall_tiles",
    ]
    for mask in range(16):
        joined = "".join(names[b] for b in (NORTH, EAST, SOUTH, WEST) if mask & b) or "none"
        inks = tile_inks(mask, Colouring(core="K", rim="C"))
        lines.append(f"    \\ mask {mask:2d}: joins {joined}")
        for y in range(8):
            lines.append("    \\   " + "".join("." if c == "K" else "R" for c in inks[y]))
        lines += _byte_rows(list(tile_rim_mask(mask)), per_row=8)
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Test card layout
# ---------------------------------------------------------------------------

def generate_testcard_data(table: InkTable) -> str:
    from dontdither.screen import ARENA_CELLS
    from dontdither.testcard import (
        BORDER_COLOURING,
        SWATCH_CELLS,
        SWATCH_COLUMNS,
        swatch_colouring,
        swatch_index_of_superpixel,
        swatch_origin_cell,
        swatch_states,
        wall_cells,
    )
    from dontdither.walls import wall_bitmap

    states = swatch_states()
    columns = [swatch_index_of_superpixel(c) for c in range(ARENA_CELLS)]
    lines = [
        "\\ " + "=" * 74,
        "\\ testcard_data.asm -- GENERATED by tools/dontdither/gen_tables.py from",
        "\\ tools/dontdither/testcard.py. Do not edit; regenerate with `uv run dd-build`.",
        "\\ " + "=" * 74,
        "",
        "\\ testcard_swatch_states: ink state of each of the 6x6 swatches, row-major.",
        ".testcard_swatch_states",
    ]
    for row in range(len(states) // SWATCH_COLUMNS):
        chunk = states[row * SWATCH_COLUMNS:(row + 1) * SWATCH_COLUMNS]
        lines.append("    EQUB " + ", ".join(f"{table.states.index(s):2d}" for s in chunk)
                     + "    \\ " + " ".join("".join(map(str, s)) for s in chunk))
    lines += [
        "",
        "\\ testcard_swatch_column: swatch column (0..5) of superpixel column sx.",
        ".testcard_swatch_column",
        *_byte_rows(columns, per_row=16),
        "",
        "\\ testcard_swatch_row_base: first swatch index (row * 6) of the swatch row",
        "\\ containing superpixel row sy.",
        ".testcard_swatch_row_base",
        *_byte_rows([c * SWATCH_COLUMNS for c in columns], per_row=16),
        "",
        f"TESTCARD_BORDER_CORE = WALL_INK_{BORDER_COLOURING.core}   \\ border wall colouring",
        f"TESTCARD_BORDER_RIM  = WALL_INK_{BORDER_COLOURING.rim}",
        f"TESTCARD_SWATCH_CELLS = {SWATCH_CELLS}   \\ character cells per swatch side",
        "",
        "\\ testcard_swatch_walls: per swatch, 4 bytes: origin cell cx, cy (top-left",
        "\\ of the 5x5-cell swatch), then core and rim ink bytes for its feature.",
        "\\ The 12 (core, rim) colourings repeat three times over the 36 swatches.",
        ".testcard_swatch_walls",
        *(
            f"    EQUB {cx:2d}, {cy:2d}, WALL_INK_{c.core}, WALL_INK_{c.rim}    \\ swatch {i:2d}: {c.core} core, {c.rim} rim"
            for i in range(len(states))
            for (cx, cy), c in [(swatch_origin_cell(i), swatch_colouring(i))]
        ),
        "TESTCARD_SWATCH_RECORD = 4",
        f"TESTCARD_SWATCH_COUNT  = {len(states)}",
        "",
        "\\ testcard_walls: 32x32 wall bitmap, 4 bytes per character row, most",
        "\\ significant bit = leftmost cell.",
        ".testcard_walls",
        *_byte_rows(list(wall_bitmap(wall_cells())), per_row=4),
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Levels
# ---------------------------------------------------------------------------

def generate_level_data(table: InkTable) -> str:
    from dontdither.levels import FACINGS, NAME_LENGTH, LevelOp, level_filepaths, parse_level

    filepaths = level_filepaths()
    levels = [parse_level(p.read_text(), p.name) for p in filepaths]
    lines = [
        "\\ " + "=" * 74,
        "\\ level_data.asm -- GENERATED by tools/dontdither/gen_tables.py from",
        "\\ levels/*.lvl. Do not edit; regenerate with `uv run dd-build`.",
        "\\ See asm/level.asm and tools/dontdither/levels.py for the format.",
        "\\ " + "=" * 74,
        "",
        "\\ Opcodes",
        *(f"LEVEL_{op.name:<6}= {op.value}" for op in LevelOp),
        "",
        "\\ Header offsets",
        "LEVEL_HEADER_SYMMETRY = 0   \\ quarter turns between copies: 1 ROT4, 2 ROT2",
        "LEVEL_HEADER_CORE     = 1   \\ wall core ink byte",
        "LEVEL_HEADER_RIM      = 2   \\ wall rim ink byte",
        "LEVEL_HEADER_FILL     = 3   \\ ink state of open cells",
        "LEVEL_HEADER_SIZE     = 4",
        "",
        f"LEVEL_COUNT = {len(levels)}",
        f"LEVEL_NAME_LENGTH = {NAME_LENGTH}",
        "",
        "\\ Address of each level's bytecode, split into low and high bytes.",
        ".level_table_lo",
        *(f"    EQUB LO(level_{i})    \\ {lv.name}" for i, lv in enumerate(levels)),
        ".level_table_hi",
        *(f"    EQUB HI(level_{i})" for i in range(len(levels))),
        "",
        "\\ level_players: per level, the number of players, then for each of 4",
        "\\ player slots: start sx, sy (superpixels, top-left of the 6x6 footprint),",
        "\\ facing (0 = N, clockwise) and ink (0 = C, 1 = M, 2 = Y, 3 = K). Unused",
        "\\ slots are zero. LEVEL_PLAYERS_RECORD bytes per level.",
        "LEVEL_PLAYERS_RECORD = 17",
        ".level_players",
        *(
            "    EQUB " + ", ".join(
                [str(len(lv.starts()))]
                + [str(v) for st, ink in zip(lv.starts(), lv.player_inks())
                   for v in (st.sx, st.sy, st.facing, "CMYK".index(ink))]
                + ["0"] * (4 * (4 - len(lv.starts())))
            ) + f"    \\ {lv.name}"
            for lv in levels
        ),
        "",
        "\\ level_names: LEVEL_NAME_LENGTH characters per level, space padded.",
        ".level_names",
        *(f'    EQUS "{lv.name:<{NAME_LENGTH}}"' for lv in levels),
    ]
    for i, (lv, filepath) in enumerate(zip(levels, filepaths)):
        code = lv.bytecode(table)
        if len(code) > 255:
            raise ValueError(f"{filepath.name}: bytecode is {len(code)} bytes; the limit is 255")
        lines += [
            "",
            f"\\ ---- Level {i}: {lv.name} ({filepath.name}) ----",
            f".level_{i}",
            f"    EQUB {lv.symmetry.value}    \\ {lv.symmetry.name}",
            f"    EQUB WALL_INK_{lv.colouring.core}, WALL_INK_{lv.colouring.rim}"
            f"    \\ walls: {lv.colouring.core} core, {lv.colouring.rim} rim",
            f"    EQUB {table.states.index(lv.fill)}    \\ fill state {lv.fill}",
            f"    EQUB LEVEL_START, {lv.start.sx}, {lv.start.sy}, {lv.start.facing}"
            f"    \\ player 0 at ({lv.start.sx}, {lv.start.sy}) facing {FACINGS[lv.start.facing]}",
        ]
        for op, x, y in lv.commands:
            lines.append(f"    EQUB LEVEL_{op.name}, {x}, {y}")
        lines.append("    EQUB LEVEL_END")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Player sprites
# ---------------------------------------------------------------------------

def generate_sprite_data() -> str:
    from dontdither.sprites import (
        CONTRAST_INK,
        FACINGS,
        FRAME_BYTES,
        frame_order,
        frame_planes,
        load_tank,
    )
    from dontdither.walls import full_byte

    tank = load_tank()
    lines = [
        "\\ " + "=" * 74,
        "\\ sprite_data.asm -- GENERATED by tools/dontdither/gen_tables.py from",
        "\\ sprites/tank.spr. Do not edit; regenerate with `uv run dd-build`.",
        "\\",
        "\\ One frame per facing (0 = N, clockwise) and alignment (0: even sx, sprite",
        "\\ starts at the left of a byte; 1: odd sx, 2 pixels in). Frame number =",
        "\\ facing * 2 + alignment. Each frame is SPRITE_FRAME_BYTES mask bytes and as",
        "\\ many select bytes, in drawing order: per superpixel row, the top raster",
        "\\ line's 4 bytes then the bottom line's. Mask pixels are ones where the",
        "\\ sprite is opaque; select pixels are ones where it shows the player's ink",
        "\\ (elsewhere the contrast ink).",
        "\\ " + "=" * 74,
        "",
        f"SPRITE_FRAME_BYTES = {FRAME_BYTES}",
        "SPRITE_FOOTPRINT   = 6      \\ superpixels per side",
        "",
        "\\ sprite_line_offsets: for frame byte i, the offset of its screen byte",
        "\\ from the address of the top raster line of its superpixel row:",
        "\\ byte * 8 + raster line within the row (0 top, 1 bottom).",
        ".sprite_line_offsets",
        *_byte_rows([byte * 8 + line % 2 for line, byte in frame_order()], per_row=8),
        "",
        "\\ Player ink and contrast ink bytes, indexed by ink (0 = C .. 3 = K).",
        ".ink_bytes",
        "    EQUB " + ", ".join(f"&{full_byte(i):02X}" for i in "CMYK") + "    \\ C, M, Y, K",
        ".contrast_ink_bytes",
        "    EQUB " + ", ".join(f"&{full_byte(CONTRAST_INK[i]):02X}" for i in "CMYK")
        + "    \\ " + ", ".join(CONTRAST_INK[i] for i in "CMYK"),
        "",
        "\\ Frame addresses, indexed by frame number.",
        ".sprite_mask_lo",
        *(f"    EQUB LO(sprite_mask_{n})" for n in range(16)),
        ".sprite_mask_hi",
        *(f"    EQUB HI(sprite_mask_{n})" for n in range(16)),
        ".sprite_select_lo",
        *(f"    EQUB LO(sprite_select_{n})" for n in range(16)),
        ".sprite_select_hi",
        *(f"    EQUB HI(sprite_select_{n})" for n in range(16)),
    ]
    for facing_number, facing in enumerate(FACINGS):
        for alignment in range(2):
            n = facing_number * 2 + alignment
            mask, select = frame_planes(tank[facing], alignment)
            lines += [
                "",
                f"\\ Frame {n}: facing {facing}, {'odd' if alignment else 'even'} sx",
                f".sprite_mask_{n}",
                *_byte_rows(list(mask), per_row=8),
                f".sprite_select_{n}",
                *_byte_rows(list(select), per_row=8),
            ]
    return "\n".join(lines) + "\n"


def generate_all(dirpath) -> None:
    """Write every generated source file into dirpath."""
    table = InkTable.load()
    dirpath.mkdir(parents=True, exist_ok=True)
    (dirpath / "ink_tables.asm").write_text(generate(table))
    (dirpath / "screen_tables.asm").write_text(generate_screen_tables())
    (dirpath / "wall_tiles.asm").write_text(generate_wall_tiles())
    (dirpath / "testcard_data.asm").write_text(generate_testcard_data(table))
    (dirpath / "level_data.asm").write_text(generate_level_data(table))
    (dirpath / "sprite_data.asm").write_text(generate_sprite_data())
