"""Choose the canonical 2x2 pattern for each of the 35 ink states.

Hard constraints:
  * every 2+2 state is a checkerboard;
  * in every 2+1+1 state the doubled ink lies on a diagonal, so repeated
    tiles form a checkerboard of it rather than one-pixel stripes (stripes
    would also look different horizontally and vertically, breaking the
    visual equivalence that colour cycling is meant to give);
  * cycling inks C->M->Y->K->C corresponds to a clockwise 90 degree rotation
    of the tile, up to a one-pixel translation of the repeating texture:
        f(cycle(s)) in translations(rotate_clockwise(cycle_inks(f(s))))

Objective (lexicographic via weights): fewest 4-pixel transitions, then
fewest 3-pixel transitions, then fewest 2-pixel transitions (equivalently,
most 1-pixel transitions). The optimum is 78/32/6/4 edges changing 1/2/3/4
pixels; without the diagonal constraint it would be 78/36/6/0.

Strict equivariance (without translation) is infeasible with checkerboards:
cycling twice swaps C<->Y and fixes the state (2,0,2,0), while two rotations
are a 180 degree rotation, which fixes a checkerboard, so the swapped
checkerboard cannot equal the original.

Run with:  uv run --group solver dd-solve-patterns
"""

from __future__ import annotations

import json

from dontdither.inks import (
    PATTERNS_FILEPATH,
    InkTable,
    adjacent_state_pairs,
    all_states,
    arrangements,
    cycle_inks,
    cycle_state,
    hamming,
    has_doubled_ink_on_diagonal,
    is_checkerboard,
    is_two_one_one,
    is_two_two,
    rotate_clockwise,
    translations,
)


def solve(time_limit_seconds: float = 300.0) -> InkTable:
    from ortools.sat.python import cp_model

    states = all_states()

    def allowed(s, p):
        if is_two_two(s):
            return is_checkerboard(p)
        if is_two_one_one(s):
            return has_doubled_ink_on_diagonal(p)
        return True

    candidates = {s: [p for p in arrangements(s) if allowed(s, p)] for s in states}

    model = cp_model.CpModel()
    chosen = {(s, p): model.NewBoolVar(f"{s}{p}") for s in states for p in candidates[s]}
    for s in states:
        model.AddExactlyOne(chosen[s, p] for p in candidates[s])

    # Colour-cycle / rotation equivariance, up to texture translation.
    for s in states:
        image_state = cycle_state(s)
        for p in candidates[s]:
            images = translations(rotate_clockwise(cycle_inks(p)))
            allowed = [chosen[image_state, q] for q in candidates[image_state] if q in images]
            model.AddBoolOr(allowed).OnlyEnforceIf(chosen[s, p])

    # One indicator per adjacent pair for its physical churn (1..4 pixels).
    cost_terms = []
    for s, t in adjacent_state_pairs(states):
        churn = {k: model.NewBoolVar("") for k in (1, 2, 3, 4)}
        model.AddExactlyOne(churn.values())
        for p in candidates[s]:
            for k, indicator in churn.items():
                matching = [chosen[t, q] for q in candidates[t] if hamming(p, q) == k]
                model.AddBoolOr(matching).OnlyEnforceIf([indicator, chosen[s, p]])
        cost_terms.append(1000 * churn[4] + 10 * churn[3] + churn[2])
    model.Minimize(sum(cost_terms))

    solver = cp_model.CpSolver()
    solver.parameters.max_time_in_seconds = time_limit_seconds
    solver.parameters.num_workers = 1  # deterministic
    solver.parameters.random_seed = 0
    status = solver.Solve(model)
    if status != cp_model.OPTIMAL:
        raise RuntimeError(f"Solver did not prove optimality: {solver.StatusName(status)}")
    return InkTable(tuple(p for s in states for p in candidates[s] if solver.Value(chosen[s, p])))


def main() -> None:
    table = solve()
    histogram = table.churn_histogram()
    document = {
        "description": (
            "Canonical 2x2 pattern per CMYK ink state. Pattern is row-major "
            "TL TR BL BR. Generated by tools/dontdither/solve_patterns.py: "
            "2+2 states are checkerboards; 2+1+1 states have the doubled ink on "
            "a diagonal; C->M->Y->K colour cycling equals a "
            "clockwise 90 degree tile rotation up to texture translation; "
            "churn minimised (proved optimal)."
        ),
        "churn_histogram": {str(k): v for k, v in histogram.items()},
        "states": [
            {"index": i, "state": list(s), "pattern": p}
            for i, (s, p) in enumerate(zip(table.states, table.patterns))
        ],
    }
    PATTERNS_FILEPATH.write_text(json.dumps(document, indent=2) + "\n")
    print(f"Wrote {PATTERNS_FILEPATH}: churn {histogram}")


if __name__ == "__main__":
    main()
